`timescale 1 ns / 10 ps
// Generated from Simulink block 
module transmitter_stub (
  input [1-1:0] m_axis_tready,
  input [32-1:0] s_axis_tdata,
  input [1-1:0] s_axis_tvalid,
  input [1-1:0] m_axis_data_tready,
  input [8-1:0] s_axis_data_tdata,
  input [1-1:0] s_axis_data_tlast,
  input [1-1:0] s_axis_data_tvalid,
  input clk,
  input transmitter_aresetn,
  input [4-1:0] transmitter_s_axi_awaddr,
  input transmitter_s_axi_awvalid,
  input [32-1:0] transmitter_s_axi_wdata,
  input [4-1:0] transmitter_s_axi_wstrb,
  input transmitter_s_axi_wvalid,
  input transmitter_s_axi_bready,
  input [4-1:0] transmitter_s_axi_araddr,
  input transmitter_s_axi_arvalid,
  input transmitter_s_axi_rready,
  output [34-1:0] m_axis_op_tdata,
  output [1-1:0] m_axis_op_tvalid,
  output [32-1:0] m_axis_tdata,
  output [1-1:0] m_axis_tvalid,
  output [16-1:0] m_axis_sim_op_1,
  output [16-1:0] m_axis_sim_op_2,
  output [16-1:0] m_axis_sim_op_3,
  output [16-1:0] m_axis_sim_op_4,
  output [16-1:0] m_axis_sim_op_5,
  output [16-1:0] m_axis_sim_op_6,
  output [16-1:0] modulation_out,
  output [1-1:0] enable_tx_out,
  output [1-1:0] enable_data_out,
  output [8-1:0] m_axis_data_tdata,
  output [1-1:0] m_axis_data_tvalid,
  output [1-1:0] s_axis_data_tready,
  output [1-1:0] m_axis_data_tlast,
  output transmitter_s_axi_awready,
  output transmitter_s_axi_wready,
  output [2-1:0] transmitter_s_axi_bresp,
  output transmitter_s_axi_bvalid,
  output transmitter_s_axi_arready,
  output [32-1:0] transmitter_s_axi_rdata,
  output [2-1:0] transmitter_s_axi_rresp,
  output transmitter_s_axi_rvalid
);
  transmitter sysgen_dut (
    .m_axis_tready(m_axis_tready),
    .s_axis_tdata(s_axis_tdata),
    .s_axis_tvalid(s_axis_tvalid),
    .m_axis_data_tready(m_axis_data_tready),
    .s_axis_data_tdata(s_axis_data_tdata),
    .s_axis_data_tlast(s_axis_data_tlast),
    .s_axis_data_tvalid(s_axis_data_tvalid),
    .clk(clk),
    .transmitter_aresetn(transmitter_aresetn),
    .transmitter_s_axi_awaddr(transmitter_s_axi_awaddr),
    .transmitter_s_axi_awvalid(transmitter_s_axi_awvalid),
    .transmitter_s_axi_wdata(transmitter_s_axi_wdata),
    .transmitter_s_axi_wstrb(transmitter_s_axi_wstrb),
    .transmitter_s_axi_wvalid(transmitter_s_axi_wvalid),
    .transmitter_s_axi_bready(transmitter_s_axi_bready),
    .transmitter_s_axi_araddr(transmitter_s_axi_araddr),
    .transmitter_s_axi_arvalid(transmitter_s_axi_arvalid),
    .transmitter_s_axi_rready(transmitter_s_axi_rready),
    .m_axis_op_tdata(m_axis_op_tdata),
    .m_axis_op_tvalid(m_axis_op_tvalid),
    .m_axis_tdata(m_axis_tdata),
    .m_axis_tvalid(m_axis_tvalid),
    .m_axis_sim_op_1(m_axis_sim_op_1),
    .m_axis_sim_op_2(m_axis_sim_op_2),
    .m_axis_sim_op_3(m_axis_sim_op_3),
    .m_axis_sim_op_4(m_axis_sim_op_4),
    .m_axis_sim_op_5(m_axis_sim_op_5),
    .m_axis_sim_op_6(m_axis_sim_op_6),
    .modulation_out(modulation_out),
    .enable_tx_out(enable_tx_out),
    .enable_data_out(enable_data_out),
    .m_axis_data_tdata(m_axis_data_tdata),
    .m_axis_data_tvalid(m_axis_data_tvalid),
    .s_axis_data_tready(s_axis_data_tready),
    .m_axis_data_tlast(m_axis_data_tlast),
    .transmitter_s_axi_awready(transmitter_s_axi_awready),
    .transmitter_s_axi_wready(transmitter_s_axi_wready),
    .transmitter_s_axi_bresp(transmitter_s_axi_bresp),
    .transmitter_s_axi_bvalid(transmitter_s_axi_bvalid),
    .transmitter_s_axi_arready(transmitter_s_axi_arready),
    .transmitter_s_axi_rdata(transmitter_s_axi_rdata),
    .transmitter_s_axi_rresp(transmitter_s_axi_rresp),
    .transmitter_s_axi_rvalid(transmitter_s_axi_rvalid)
  );
endmodule
