# Note: This file is produced automatically, and will be overwritten the next
# time you press "Generate" in System Generator. 
#


namespace eval ::xilinx::dsp::planaheaddriver {
	set VHDL2008Support 1
	set Compilation {IP Catalog}
	set CompilationFlow {IP}
	set CreateInterfaceDocument {off}
	set DSPDevice {xczu28dr}
	set DSPFamily {zynquplus}
	set DSPPackage {ffvg1517}
	set DSPSpeed {-2-e}
	set FPGAClockPeriod 7.8125
	set GenerateTestBench 0
	set HDLLanguage {verilog}
	set IPOOCCacheRootPath {C:/Users/alaid/AppData/Local/Xilinx/Sysgen/SysgenVivado/win64.o/ip}
	set IP_Auto_Infer {1}
	set IP_Categories_Text {System_Generator_for_DSP}
	set IP_Common_Repos {0}
	set IP_Description {}
	set IP_Dir {}
	set IP_Library_Text {SysGen}
	set IP_LifeCycle_Menu {2}
	set IP_Logo {sysgen_icon_100.png}
	set IP_Name {}
	set IP_Revision {307469123}
	set IP_Socket_IP {0}
	set IP_Socket_IP_Proj_Path {}
	set IP_Vendor_Text {User_Company}
	set IP_Version_Text {1.0}
	set ImplStrategyName {Vivado Implementation Defaults}
	set PostProjectCreationProc {dsp_package_for_vivado_ip_integrator}
	set Project {transmitter}
	set ProjectFiles {
		{{conv_pkg.v}}
		{{synth_reg.v}}
		{{synth_reg_w_init.v}}
		{{convert_type.v}}
		{{xlclockdriver_rd.v}}
		{{vivado_ip.tcl}}
		{{transmitter.mdd}}
		{{transmitter_hw.h}}
		{{transmitter.h}}
		{{transmitter_sinit.c}}
		{{transmitter.c}}
		{{transmitter_linux.c}}
		{{transmitter.mtcl}}
		{{Makefile.mak}}
		{{index.html}}
		{{transmitter_entity_declarations.v}}
		{{transmitter.v}}
		{{transmitter_clock.xdc}}
		{{transmitter.xdc}}
	}
	set SimPeriod 7.8125e-09
	set SimTime 0.00125
	set SimulationTime {1250215.62500000 ns}
	set SynthStrategyName {Vivado Synthesis Defaults}
	set SynthesisTool {Vivado}
	set TargetDir {C:/test/generate_transmitter}
	set TopLevelModule {transmitter}
	set TopLevelSimulinkHandle 1463
	set TopLevelPortInterface {}
	dict set TopLevelPortInterface s_axis_data_tvalid Name {s_axis_data_tvalid}
	dict set TopLevelPortInterface s_axis_data_tvalid Type Bool
	dict set TopLevelPortInterface s_axis_data_tvalid ArithmeticType xlUnsigned
	dict set TopLevelPortInterface s_axis_data_tvalid BinaryPoint 0
	dict set TopLevelPortInterface s_axis_data_tvalid Width 1
	dict set TopLevelPortInterface s_axis_data_tvalid DatFile {model_v6_15022023_transmitter_s_axis_data_s_axis_data_tvalid.dat}
	dict set TopLevelPortInterface s_axis_data_tvalid IconText {s_axis_data_tvalid}
	dict set TopLevelPortInterface s_axis_data_tvalid Direction in
	dict set TopLevelPortInterface s_axis_data_tvalid Period 1
	dict set TopLevelPortInterface s_axis_data_tvalid Interface 0
	dict set TopLevelPortInterface s_axis_data_tvalid InterfaceName {}
	dict set TopLevelPortInterface s_axis_data_tvalid InterfaceString {DATA}
	dict set TopLevelPortInterface s_axis_data_tvalid ClockDomain {transmitter}
	dict set TopLevelPortInterface s_axis_data_tvalid Locs {}
	dict set TopLevelPortInterface s_axis_data_tvalid IOStandard {}
	dict set TopLevelPortInterface s_axis_data_tlast Name {s_axis_data_tlast}
	dict set TopLevelPortInterface s_axis_data_tlast Type UFix_1_0
	dict set TopLevelPortInterface s_axis_data_tlast ArithmeticType xlUnsigned
	dict set TopLevelPortInterface s_axis_data_tlast BinaryPoint 0
	dict set TopLevelPortInterface s_axis_data_tlast Width 1
	dict set TopLevelPortInterface s_axis_data_tlast DatFile {model_v6_15022023_transmitter_s_axis_data_s_axis_data_tlast.dat}
	dict set TopLevelPortInterface s_axis_data_tlast IconText {s_axis_data_tlast}
	dict set TopLevelPortInterface s_axis_data_tlast Direction in
	dict set TopLevelPortInterface s_axis_data_tlast Period 1
	dict set TopLevelPortInterface s_axis_data_tlast Interface 0
	dict set TopLevelPortInterface s_axis_data_tlast InterfaceName {}
	dict set TopLevelPortInterface s_axis_data_tlast InterfaceString {DATA}
	dict set TopLevelPortInterface s_axis_data_tlast ClockDomain {transmitter}
	dict set TopLevelPortInterface s_axis_data_tlast Locs {}
	dict set TopLevelPortInterface s_axis_data_tlast IOStandard {}
	dict set TopLevelPortInterface s_axis_data_tdata Name {s_axis_data_tdata}
	dict set TopLevelPortInterface s_axis_data_tdata Type UFix_8_0
	dict set TopLevelPortInterface s_axis_data_tdata ArithmeticType xlUnsigned
	dict set TopLevelPortInterface s_axis_data_tdata BinaryPoint 0
	dict set TopLevelPortInterface s_axis_data_tdata Width 8
	dict set TopLevelPortInterface s_axis_data_tdata DatFile {model_v6_15022023_transmitter_s_axis_data_s_axis_data_tdata.dat}
	dict set TopLevelPortInterface s_axis_data_tdata IconText {s_axis_data_tdata}
	dict set TopLevelPortInterface s_axis_data_tdata Direction in
	dict set TopLevelPortInterface s_axis_data_tdata Period 1
	dict set TopLevelPortInterface s_axis_data_tdata Interface 0
	dict set TopLevelPortInterface s_axis_data_tdata InterfaceName {}
	dict set TopLevelPortInterface s_axis_data_tdata InterfaceString {DATA}
	dict set TopLevelPortInterface s_axis_data_tdata ClockDomain {transmitter}
	dict set TopLevelPortInterface s_axis_data_tdata Locs {}
	dict set TopLevelPortInterface s_axis_data_tdata IOStandard {}
	dict set TopLevelPortInterface m_axis_data_tready Name {m_axis_data_tready}
	dict set TopLevelPortInterface m_axis_data_tready Type Bool
	dict set TopLevelPortInterface m_axis_data_tready ArithmeticType xlUnsigned
	dict set TopLevelPortInterface m_axis_data_tready BinaryPoint 0
	dict set TopLevelPortInterface m_axis_data_tready Width 1
	dict set TopLevelPortInterface m_axis_data_tready DatFile {model_v6_15022023_transmitter_s_axis_data_m_axis_data_tready.dat}
	dict set TopLevelPortInterface m_axis_data_tready IconText {m_axis_data_tready}
	dict set TopLevelPortInterface m_axis_data_tready Direction in
	dict set TopLevelPortInterface m_axis_data_tready Period 1
	dict set TopLevelPortInterface m_axis_data_tready Interface 0
	dict set TopLevelPortInterface m_axis_data_tready InterfaceName {}
	dict set TopLevelPortInterface m_axis_data_tready InterfaceString {DATA}
	dict set TopLevelPortInterface m_axis_data_tready ClockDomain {transmitter}
	dict set TopLevelPortInterface m_axis_data_tready Locs {}
	dict set TopLevelPortInterface m_axis_data_tready IOStandard {}
	dict set TopLevelPortInterface s_axis_tvalid Name {s_axis_tvalid}
	dict set TopLevelPortInterface s_axis_tvalid Type Bool
	dict set TopLevelPortInterface s_axis_tvalid ArithmeticType xlUnsigned
	dict set TopLevelPortInterface s_axis_tvalid BinaryPoint 0
	dict set TopLevelPortInterface s_axis_tvalid Width 1
	dict set TopLevelPortInterface s_axis_tvalid DatFile {model_v6_15022023_transmitter_s_axis_tvalid.dat}
	dict set TopLevelPortInterface s_axis_tvalid IconText {s_axis_tvalid}
	dict set TopLevelPortInterface s_axis_tvalid Direction in
	dict set TopLevelPortInterface s_axis_tvalid Period 1280
	dict set TopLevelPortInterface s_axis_tvalid Interface 0
	dict set TopLevelPortInterface s_axis_tvalid InterfaceName {}
	dict set TopLevelPortInterface s_axis_tvalid InterfaceString {DATA}
	dict set TopLevelPortInterface s_axis_tvalid ClockDomain {transmitter}
	dict set TopLevelPortInterface s_axis_tvalid Locs {}
	dict set TopLevelPortInterface s_axis_tvalid IOStandard {}
	dict set TopLevelPortInterface s_axis_tdata Name {s_axis_tdata}
	dict set TopLevelPortInterface s_axis_tdata Type UFix_32_0
	dict set TopLevelPortInterface s_axis_tdata ArithmeticType xlUnsigned
	dict set TopLevelPortInterface s_axis_tdata BinaryPoint 0
	dict set TopLevelPortInterface s_axis_tdata Width 32
	dict set TopLevelPortInterface s_axis_tdata DatFile {model_v6_15022023_transmitter_s_axis_tdata.dat}
	dict set TopLevelPortInterface s_axis_tdata IconText {s_axis_tdata}
	dict set TopLevelPortInterface s_axis_tdata Direction in
	dict set TopLevelPortInterface s_axis_tdata Period 1280
	dict set TopLevelPortInterface s_axis_tdata Interface 0
	dict set TopLevelPortInterface s_axis_tdata InterfaceName {}
	dict set TopLevelPortInterface s_axis_tdata InterfaceString {DATA}
	dict set TopLevelPortInterface s_axis_tdata ClockDomain {transmitter}
	dict set TopLevelPortInterface s_axis_tdata Locs {}
	dict set TopLevelPortInterface s_axis_tdata IOStandard {}
	dict set TopLevelPortInterface m_axis_tready Name {m_axis_tready}
	dict set TopLevelPortInterface m_axis_tready Type Bool
	dict set TopLevelPortInterface m_axis_tready ArithmeticType xlUnsigned
	dict set TopLevelPortInterface m_axis_tready BinaryPoint 0
	dict set TopLevelPortInterface m_axis_tready Width 1
	dict set TopLevelPortInterface m_axis_tready DatFile {model_v6_15022023_transmitter_m_axis_tready.dat}
	dict set TopLevelPortInterface m_axis_tready IconText {m_axis_tready}
	dict set TopLevelPortInterface m_axis_tready Direction in
	dict set TopLevelPortInterface m_axis_tready Period 1
	dict set TopLevelPortInterface m_axis_tready Interface 0
	dict set TopLevelPortInterface m_axis_tready InterfaceName {}
	dict set TopLevelPortInterface m_axis_tready InterfaceString {DATA}
	dict set TopLevelPortInterface m_axis_tready ClockDomain {transmitter}
	dict set TopLevelPortInterface m_axis_tready Locs {}
	dict set TopLevelPortInterface m_axis_tready IOStandard {}
	dict set TopLevelPortInterface m_axis_op_tdata Name {m_axis_op_tdata}
	dict set TopLevelPortInterface m_axis_op_tdata Type UFix_34_0
	dict set TopLevelPortInterface m_axis_op_tdata ArithmeticType xlUnsigned
	dict set TopLevelPortInterface m_axis_op_tdata BinaryPoint 0
	dict set TopLevelPortInterface m_axis_op_tdata Width 34
	dict set TopLevelPortInterface m_axis_op_tdata DatFile {model_v6_15022023_transmitter_m_axis_op_tdata.dat}
	dict set TopLevelPortInterface m_axis_op_tdata IconText {m_axis_op_tdata}
	dict set TopLevelPortInterface m_axis_op_tdata Direction out
	dict set TopLevelPortInterface m_axis_op_tdata Period 1
	dict set TopLevelPortInterface m_axis_op_tdata Interface 0
	dict set TopLevelPortInterface m_axis_op_tdata InterfaceName {}
	dict set TopLevelPortInterface m_axis_op_tdata InterfaceString {DATA}
	dict set TopLevelPortInterface m_axis_op_tdata ClockDomain {transmitter}
	dict set TopLevelPortInterface m_axis_op_tdata Locs {}
	dict set TopLevelPortInterface m_axis_op_tdata IOStandard {}
	dict set TopLevelPortInterface m_axis_op_tvalid Name {m_axis_op_tvalid}
	dict set TopLevelPortInterface m_axis_op_tvalid Type Bool
	dict set TopLevelPortInterface m_axis_op_tvalid ArithmeticType xlUnsigned
	dict set TopLevelPortInterface m_axis_op_tvalid BinaryPoint 0
	dict set TopLevelPortInterface m_axis_op_tvalid Width 1
	dict set TopLevelPortInterface m_axis_op_tvalid DatFile {model_v6_15022023_transmitter_m_axis_op_tvalid.dat}
	dict set TopLevelPortInterface m_axis_op_tvalid IconText {m_axis_op_tvalid}
	dict set TopLevelPortInterface m_axis_op_tvalid Direction out
	dict set TopLevelPortInterface m_axis_op_tvalid Period 1
	dict set TopLevelPortInterface m_axis_op_tvalid Interface 0
	dict set TopLevelPortInterface m_axis_op_tvalid InterfaceName {}
	dict set TopLevelPortInterface m_axis_op_tvalid InterfaceString {DATA}
	dict set TopLevelPortInterface m_axis_op_tvalid ClockDomain {transmitter}
	dict set TopLevelPortInterface m_axis_op_tvalid Locs {}
	dict set TopLevelPortInterface m_axis_op_tvalid IOStandard {}
	dict set TopLevelPortInterface m_axis_tdata Name {m_axis_tdata}
	dict set TopLevelPortInterface m_axis_tdata Type UFix_32_0
	dict set TopLevelPortInterface m_axis_tdata ArithmeticType xlUnsigned
	dict set TopLevelPortInterface m_axis_tdata BinaryPoint 0
	dict set TopLevelPortInterface m_axis_tdata Width 32
	dict set TopLevelPortInterface m_axis_tdata DatFile {model_v6_15022023_transmitter_m_axis_tdata.dat}
	dict set TopLevelPortInterface m_axis_tdata IconText {m_axis_tdata}
	dict set TopLevelPortInterface m_axis_tdata Direction out
	dict set TopLevelPortInterface m_axis_tdata Period 1
	dict set TopLevelPortInterface m_axis_tdata Interface 0
	dict set TopLevelPortInterface m_axis_tdata InterfaceName {}
	dict set TopLevelPortInterface m_axis_tdata InterfaceString {DATA}
	dict set TopLevelPortInterface m_axis_tdata ClockDomain {transmitter}
	dict set TopLevelPortInterface m_axis_tdata Locs {}
	dict set TopLevelPortInterface m_axis_tdata IOStandard {}
	dict set TopLevelPortInterface m_axis_tvalid Name {m_axis_tvalid}
	dict set TopLevelPortInterface m_axis_tvalid Type Bool
	dict set TopLevelPortInterface m_axis_tvalid ArithmeticType xlUnsigned
	dict set TopLevelPortInterface m_axis_tvalid BinaryPoint 0
	dict set TopLevelPortInterface m_axis_tvalid Width 1
	dict set TopLevelPortInterface m_axis_tvalid DatFile {model_v6_15022023_transmitter_m_axis_tvalid.dat}
	dict set TopLevelPortInterface m_axis_tvalid IconText {m_axis_tvalid}
	dict set TopLevelPortInterface m_axis_tvalid Direction out
	dict set TopLevelPortInterface m_axis_tvalid Period 1
	dict set TopLevelPortInterface m_axis_tvalid Interface 0
	dict set TopLevelPortInterface m_axis_tvalid InterfaceName {}
	dict set TopLevelPortInterface m_axis_tvalid InterfaceString {DATA}
	dict set TopLevelPortInterface m_axis_tvalid ClockDomain {transmitter}
	dict set TopLevelPortInterface m_axis_tvalid Locs {}
	dict set TopLevelPortInterface m_axis_tvalid IOStandard {}
	dict set TopLevelPortInterface m_axis_sim_op_1 Name {m_axis_sim_op_1}
	dict set TopLevelPortInterface m_axis_sim_op_1 Type Fix_16_15
	dict set TopLevelPortInterface m_axis_sim_op_1 ArithmeticType xlSigned
	dict set TopLevelPortInterface m_axis_sim_op_1 BinaryPoint 15
	dict set TopLevelPortInterface m_axis_sim_op_1 Width 16
	dict set TopLevelPortInterface m_axis_sim_op_1 DatFile {model_v6_15022023_transmitter_m_axis_sim_op_1.dat}
	dict set TopLevelPortInterface m_axis_sim_op_1 IconText {m_axis_sim_op_1}
	dict set TopLevelPortInterface m_axis_sim_op_1 Direction out
	dict set TopLevelPortInterface m_axis_sim_op_1 Period 1
	dict set TopLevelPortInterface m_axis_sim_op_1 Interface 0
	dict set TopLevelPortInterface m_axis_sim_op_1 InterfaceName {}
	dict set TopLevelPortInterface m_axis_sim_op_1 InterfaceString {DATA}
	dict set TopLevelPortInterface m_axis_sim_op_1 ClockDomain {transmitter}
	dict set TopLevelPortInterface m_axis_sim_op_1 Locs {}
	dict set TopLevelPortInterface m_axis_sim_op_1 IOStandard {}
	dict set TopLevelPortInterface m_axis_sim_op_2 Name {m_axis_sim_op_2}
	dict set TopLevelPortInterface m_axis_sim_op_2 Type Fix_16_15
	dict set TopLevelPortInterface m_axis_sim_op_2 ArithmeticType xlSigned
	dict set TopLevelPortInterface m_axis_sim_op_2 BinaryPoint 15
	dict set TopLevelPortInterface m_axis_sim_op_2 Width 16
	dict set TopLevelPortInterface m_axis_sim_op_2 DatFile {model_v6_15022023_transmitter_m_axis_sim_op_2.dat}
	dict set TopLevelPortInterface m_axis_sim_op_2 IconText {m_axis_sim_op_2}
	dict set TopLevelPortInterface m_axis_sim_op_2 Direction out
	dict set TopLevelPortInterface m_axis_sim_op_2 Period 320
	dict set TopLevelPortInterface m_axis_sim_op_2 Interface 0
	dict set TopLevelPortInterface m_axis_sim_op_2 InterfaceName {}
	dict set TopLevelPortInterface m_axis_sim_op_2 InterfaceString {DATA}
	dict set TopLevelPortInterface m_axis_sim_op_2 ClockDomain {transmitter}
	dict set TopLevelPortInterface m_axis_sim_op_2 Locs {}
	dict set TopLevelPortInterface m_axis_sim_op_2 IOStandard {}
	dict set TopLevelPortInterface m_axis_sim_op_3 Name {m_axis_sim_op_3}
	dict set TopLevelPortInterface m_axis_sim_op_3 Type Fix_16_14
	dict set TopLevelPortInterface m_axis_sim_op_3 ArithmeticType xlSigned
	dict set TopLevelPortInterface m_axis_sim_op_3 BinaryPoint 14
	dict set TopLevelPortInterface m_axis_sim_op_3 Width 16
	dict set TopLevelPortInterface m_axis_sim_op_3 DatFile {model_v6_15022023_transmitter_m_axis_sim_op_3.dat}
	dict set TopLevelPortInterface m_axis_sim_op_3 IconText {m_axis_sim_op_3}
	dict set TopLevelPortInterface m_axis_sim_op_3 Direction out
	dict set TopLevelPortInterface m_axis_sim_op_3 Period 1280
	dict set TopLevelPortInterface m_axis_sim_op_3 Interface 0
	dict set TopLevelPortInterface m_axis_sim_op_3 InterfaceName {}
	dict set TopLevelPortInterface m_axis_sim_op_3 InterfaceString {DATA}
	dict set TopLevelPortInterface m_axis_sim_op_3 ClockDomain {transmitter}
	dict set TopLevelPortInterface m_axis_sim_op_3 Locs {}
	dict set TopLevelPortInterface m_axis_sim_op_3 IOStandard {}
	dict set TopLevelPortInterface m_axis_sim_op_4 Name {m_axis_sim_op_4}
	dict set TopLevelPortInterface m_axis_sim_op_4 Type Fix_16_15
	dict set TopLevelPortInterface m_axis_sim_op_4 ArithmeticType xlSigned
	dict set TopLevelPortInterface m_axis_sim_op_4 BinaryPoint 15
	dict set TopLevelPortInterface m_axis_sim_op_4 Width 16
	dict set TopLevelPortInterface m_axis_sim_op_4 DatFile {model_v6_15022023_transmitter_m_axis_sim_op_4.dat}
	dict set TopLevelPortInterface m_axis_sim_op_4 IconText {m_axis_sim_op_4}
	dict set TopLevelPortInterface m_axis_sim_op_4 Direction out
	dict set TopLevelPortInterface m_axis_sim_op_4 Period 1
	dict set TopLevelPortInterface m_axis_sim_op_4 Interface 0
	dict set TopLevelPortInterface m_axis_sim_op_4 InterfaceName {}
	dict set TopLevelPortInterface m_axis_sim_op_4 InterfaceString {DATA}
	dict set TopLevelPortInterface m_axis_sim_op_4 ClockDomain {transmitter}
	dict set TopLevelPortInterface m_axis_sim_op_4 Locs {}
	dict set TopLevelPortInterface m_axis_sim_op_4 IOStandard {}
	dict set TopLevelPortInterface m_axis_sim_op_5 Name {m_axis_sim_op_5}
	dict set TopLevelPortInterface m_axis_sim_op_5 Type Fix_16_15
	dict set TopLevelPortInterface m_axis_sim_op_5 ArithmeticType xlSigned
	dict set TopLevelPortInterface m_axis_sim_op_5 BinaryPoint 15
	dict set TopLevelPortInterface m_axis_sim_op_5 Width 16
	dict set TopLevelPortInterface m_axis_sim_op_5 DatFile {model_v6_15022023_transmitter_m_axis_sim_op_5.dat}
	dict set TopLevelPortInterface m_axis_sim_op_5 IconText {m_axis_sim_op_5}
	dict set TopLevelPortInterface m_axis_sim_op_5 Direction out
	dict set TopLevelPortInterface m_axis_sim_op_5 Period 320
	dict set TopLevelPortInterface m_axis_sim_op_5 Interface 0
	dict set TopLevelPortInterface m_axis_sim_op_5 InterfaceName {}
	dict set TopLevelPortInterface m_axis_sim_op_5 InterfaceString {DATA}
	dict set TopLevelPortInterface m_axis_sim_op_5 ClockDomain {transmitter}
	dict set TopLevelPortInterface m_axis_sim_op_5 Locs {}
	dict set TopLevelPortInterface m_axis_sim_op_5 IOStandard {}
	dict set TopLevelPortInterface m_axis_sim_op_6 Name {m_axis_sim_op_6}
	dict set TopLevelPortInterface m_axis_sim_op_6 Type Fix_16_14
	dict set TopLevelPortInterface m_axis_sim_op_6 ArithmeticType xlSigned
	dict set TopLevelPortInterface m_axis_sim_op_6 BinaryPoint 14
	dict set TopLevelPortInterface m_axis_sim_op_6 Width 16
	dict set TopLevelPortInterface m_axis_sim_op_6 DatFile {model_v6_15022023_transmitter_m_axis_sim_op_6.dat}
	dict set TopLevelPortInterface m_axis_sim_op_6 IconText {m_axis_sim_op_6}
	dict set TopLevelPortInterface m_axis_sim_op_6 Direction out
	dict set TopLevelPortInterface m_axis_sim_op_6 Period 1280
	dict set TopLevelPortInterface m_axis_sim_op_6 Interface 0
	dict set TopLevelPortInterface m_axis_sim_op_6 InterfaceName {}
	dict set TopLevelPortInterface m_axis_sim_op_6 InterfaceString {DATA}
	dict set TopLevelPortInterface m_axis_sim_op_6 ClockDomain {transmitter}
	dict set TopLevelPortInterface m_axis_sim_op_6 Locs {}
	dict set TopLevelPortInterface m_axis_sim_op_6 IOStandard {}
	dict set TopLevelPortInterface modulation_out Name {modulation_out}
	dict set TopLevelPortInterface modulation_out Type UFix_16_0
	dict set TopLevelPortInterface modulation_out ArithmeticType xlUnsigned
	dict set TopLevelPortInterface modulation_out BinaryPoint 0
	dict set TopLevelPortInterface modulation_out Width 16
	dict set TopLevelPortInterface modulation_out DatFile {model_v6_15022023_transmitter_config_modulation_out.dat}
	dict set TopLevelPortInterface modulation_out IconText {modulation_out}
	dict set TopLevelPortInterface modulation_out Direction out
	dict set TopLevelPortInterface modulation_out Period 1280
	dict set TopLevelPortInterface modulation_out Interface 0
	dict set TopLevelPortInterface modulation_out InterfaceName {}
	dict set TopLevelPortInterface modulation_out InterfaceString {DATA}
	dict set TopLevelPortInterface modulation_out ClockDomain {transmitter}
	dict set TopLevelPortInterface modulation_out Locs {}
	dict set TopLevelPortInterface modulation_out IOStandard {}
	dict set TopLevelPortInterface enable_tx_out Name {enable_tx_out}
	dict set TopLevelPortInterface enable_tx_out Type Bool
	dict set TopLevelPortInterface enable_tx_out ArithmeticType xlUnsigned
	dict set TopLevelPortInterface enable_tx_out BinaryPoint 0
	dict set TopLevelPortInterface enable_tx_out Width 1
	dict set TopLevelPortInterface enable_tx_out DatFile {model_v6_15022023_transmitter_config_enable_tx_out.dat}
	dict set TopLevelPortInterface enable_tx_out IconText {enable_tx_out}
	dict set TopLevelPortInterface enable_tx_out Direction out
	dict set TopLevelPortInterface enable_tx_out Period 1280
	dict set TopLevelPortInterface enable_tx_out Interface 0
	dict set TopLevelPortInterface enable_tx_out InterfaceName {}
	dict set TopLevelPortInterface enable_tx_out InterfaceString {DATA}
	dict set TopLevelPortInterface enable_tx_out ClockDomain {transmitter}
	dict set TopLevelPortInterface enable_tx_out Locs {}
	dict set TopLevelPortInterface enable_tx_out IOStandard {}
	dict set TopLevelPortInterface enable_data_out Name {enable_data_out}
	dict set TopLevelPortInterface enable_data_out Type Bool
	dict set TopLevelPortInterface enable_data_out ArithmeticType xlUnsigned
	dict set TopLevelPortInterface enable_data_out BinaryPoint 0
	dict set TopLevelPortInterface enable_data_out Width 1
	dict set TopLevelPortInterface enable_data_out DatFile {model_v6_15022023_transmitter_config_enable_data_out.dat}
	dict set TopLevelPortInterface enable_data_out IconText {enable_data_out}
	dict set TopLevelPortInterface enable_data_out Direction out
	dict set TopLevelPortInterface enable_data_out Period 1280
	dict set TopLevelPortInterface enable_data_out Interface 0
	dict set TopLevelPortInterface enable_data_out InterfaceName {}
	dict set TopLevelPortInterface enable_data_out InterfaceString {DATA}
	dict set TopLevelPortInterface enable_data_out ClockDomain {transmitter}
	dict set TopLevelPortInterface enable_data_out Locs {}
	dict set TopLevelPortInterface enable_data_out IOStandard {}
	dict set TopLevelPortInterface m_axis_data_tdata Name {m_axis_data_tdata}
	dict set TopLevelPortInterface m_axis_data_tdata Type UFix_8_0
	dict set TopLevelPortInterface m_axis_data_tdata ArithmeticType xlUnsigned
	dict set TopLevelPortInterface m_axis_data_tdata BinaryPoint 0
	dict set TopLevelPortInterface m_axis_data_tdata Width 8
	dict set TopLevelPortInterface m_axis_data_tdata DatFile {model_v6_15022023_transmitter_s_axis_data_m_axis_data_tdata.dat}
	dict set TopLevelPortInterface m_axis_data_tdata IconText {m_axis_data_tdata}
	dict set TopLevelPortInterface m_axis_data_tdata Direction out
	dict set TopLevelPortInterface m_axis_data_tdata Period 1
	dict set TopLevelPortInterface m_axis_data_tdata Interface 0
	dict set TopLevelPortInterface m_axis_data_tdata InterfaceName {}
	dict set TopLevelPortInterface m_axis_data_tdata InterfaceString {DATA}
	dict set TopLevelPortInterface m_axis_data_tdata ClockDomain {transmitter}
	dict set TopLevelPortInterface m_axis_data_tdata Locs {}
	dict set TopLevelPortInterface m_axis_data_tdata IOStandard {}
	dict set TopLevelPortInterface m_axis_data_tvalid Name {m_axis_data_tvalid}
	dict set TopLevelPortInterface m_axis_data_tvalid Type Bool
	dict set TopLevelPortInterface m_axis_data_tvalid ArithmeticType xlUnsigned
	dict set TopLevelPortInterface m_axis_data_tvalid BinaryPoint 0
	dict set TopLevelPortInterface m_axis_data_tvalid Width 1
	dict set TopLevelPortInterface m_axis_data_tvalid DatFile {model_v6_15022023_transmitter_s_axis_data_m_axis_data_tvalid.dat}
	dict set TopLevelPortInterface m_axis_data_tvalid IconText {m_axis_data_tvalid}
	dict set TopLevelPortInterface m_axis_data_tvalid Direction out
	dict set TopLevelPortInterface m_axis_data_tvalid Period 1
	dict set TopLevelPortInterface m_axis_data_tvalid Interface 0
	dict set TopLevelPortInterface m_axis_data_tvalid InterfaceName {}
	dict set TopLevelPortInterface m_axis_data_tvalid InterfaceString {DATA}
	dict set TopLevelPortInterface m_axis_data_tvalid ClockDomain {transmitter}
	dict set TopLevelPortInterface m_axis_data_tvalid Locs {}
	dict set TopLevelPortInterface m_axis_data_tvalid IOStandard {}
	dict set TopLevelPortInterface s_axis_data_tready Name {s_axis_data_tready}
	dict set TopLevelPortInterface s_axis_data_tready Type Bool
	dict set TopLevelPortInterface s_axis_data_tready ArithmeticType xlUnsigned
	dict set TopLevelPortInterface s_axis_data_tready BinaryPoint 0
	dict set TopLevelPortInterface s_axis_data_tready Width 1
	dict set TopLevelPortInterface s_axis_data_tready DatFile {model_v6_15022023_transmitter_s_axis_data_s_axis_data_tready.dat}
	dict set TopLevelPortInterface s_axis_data_tready IconText {s_axis_data_tready}
	dict set TopLevelPortInterface s_axis_data_tready Direction out
	dict set TopLevelPortInterface s_axis_data_tready Period 1
	dict set TopLevelPortInterface s_axis_data_tready Interface 0
	dict set TopLevelPortInterface s_axis_data_tready InterfaceName {}
	dict set TopLevelPortInterface s_axis_data_tready InterfaceString {DATA}
	dict set TopLevelPortInterface s_axis_data_tready ClockDomain {transmitter}
	dict set TopLevelPortInterface s_axis_data_tready Locs {}
	dict set TopLevelPortInterface s_axis_data_tready IOStandard {}
	dict set TopLevelPortInterface m_axis_data_tlast Name {m_axis_data_tlast}
	dict set TopLevelPortInterface m_axis_data_tlast Type UFix_1_0
	dict set TopLevelPortInterface m_axis_data_tlast ArithmeticType xlUnsigned
	dict set TopLevelPortInterface m_axis_data_tlast BinaryPoint 0
	dict set TopLevelPortInterface m_axis_data_tlast Width 1
	dict set TopLevelPortInterface m_axis_data_tlast DatFile {model_v6_15022023_transmitter_s_axis_data_m_axis_data_tlast.dat}
	dict set TopLevelPortInterface m_axis_data_tlast IconText {m_axis_data_tlast}
	dict set TopLevelPortInterface m_axis_data_tlast Direction out
	dict set TopLevelPortInterface m_axis_data_tlast Period 1
	dict set TopLevelPortInterface m_axis_data_tlast Interface 0
	dict set TopLevelPortInterface m_axis_data_tlast InterfaceName {}
	dict set TopLevelPortInterface m_axis_data_tlast InterfaceString {DATA}
	dict set TopLevelPortInterface m_axis_data_tlast ClockDomain {transmitter}
	dict set TopLevelPortInterface m_axis_data_tlast Locs {}
	dict set TopLevelPortInterface m_axis_data_tlast IOStandard {}
	dict set TopLevelPortInterface transmitter_aresetn Name {transmitter_aresetn}
	dict set TopLevelPortInterface transmitter_aresetn Type -
	dict set TopLevelPortInterface transmitter_aresetn ArithmeticType xlUnsigned
	dict set TopLevelPortInterface transmitter_aresetn BinaryPoint 0
	dict set TopLevelPortInterface transmitter_aresetn Width 1
	dict set TopLevelPortInterface transmitter_aresetn DatFile {}
	dict set TopLevelPortInterface transmitter_aresetn IconText {transmitter_aresetn}
	dict set TopLevelPortInterface transmitter_aresetn Direction in
	dict set TopLevelPortInterface transmitter_aresetn Period 1
	dict set TopLevelPortInterface transmitter_aresetn Interface 8
	dict set TopLevelPortInterface transmitter_aresetn InterfaceName {}
	dict set TopLevelPortInterface transmitter_aresetn InterfaceString {ARESETN}
	dict set TopLevelPortInterface transmitter_aresetn ClockDomain {}
	dict set TopLevelPortInterface transmitter_aresetn Locs {}
	dict set TopLevelPortInterface transmitter_aresetn IOStandard {}
	dict set TopLevelPortInterface transmitter_s_axi_awaddr Name {transmitter_s_axi_awaddr}
	dict set TopLevelPortInterface transmitter_s_axi_awaddr Type -
	dict set TopLevelPortInterface transmitter_s_axi_awaddr ArithmeticType xlUnsigned
	dict set TopLevelPortInterface transmitter_s_axi_awaddr BinaryPoint 0
	dict set TopLevelPortInterface transmitter_s_axi_awaddr Width 4
	dict set TopLevelPortInterface transmitter_s_axi_awaddr DatFile {}
	dict set TopLevelPortInterface transmitter_s_axi_awaddr IconText {transmitter_s_axi_awaddr}
	dict set TopLevelPortInterface transmitter_s_axi_awaddr Direction in
	dict set TopLevelPortInterface transmitter_s_axi_awaddr Period 1
	dict set TopLevelPortInterface transmitter_s_axi_awaddr Interface 5
	dict set TopLevelPortInterface transmitter_s_axi_awaddr InterfaceName {}
	dict set TopLevelPortInterface transmitter_s_axi_awaddr InterfaceString {WIRE_AXI_LITE}
	dict set TopLevelPortInterface transmitter_s_axi_awaddr ClockDomain {}
	dict set TopLevelPortInterface transmitter_s_axi_awaddr Locs {}
	dict set TopLevelPortInterface transmitter_s_axi_awaddr IOStandard {}
	dict set TopLevelPortInterface transmitter_s_axi_awvalid Name {transmitter_s_axi_awvalid}
	dict set TopLevelPortInterface transmitter_s_axi_awvalid Type -
	dict set TopLevelPortInterface transmitter_s_axi_awvalid ArithmeticType xlUnsigned
	dict set TopLevelPortInterface transmitter_s_axi_awvalid BinaryPoint 0
	dict set TopLevelPortInterface transmitter_s_axi_awvalid Width 1
	dict set TopLevelPortInterface transmitter_s_axi_awvalid DatFile {}
	dict set TopLevelPortInterface transmitter_s_axi_awvalid IconText {transmitter_s_axi_awvalid}
	dict set TopLevelPortInterface transmitter_s_axi_awvalid Direction in
	dict set TopLevelPortInterface transmitter_s_axi_awvalid Period 1
	dict set TopLevelPortInterface transmitter_s_axi_awvalid Interface 5
	dict set TopLevelPortInterface transmitter_s_axi_awvalid InterfaceName {}
	dict set TopLevelPortInterface transmitter_s_axi_awvalid InterfaceString {WIRE_AXI_LITE}
	dict set TopLevelPortInterface transmitter_s_axi_awvalid ClockDomain {}
	dict set TopLevelPortInterface transmitter_s_axi_awvalid Locs {}
	dict set TopLevelPortInterface transmitter_s_axi_awvalid IOStandard {}
	dict set TopLevelPortInterface transmitter_s_axi_awready Name {transmitter_s_axi_awready}
	dict set TopLevelPortInterface transmitter_s_axi_awready Type -
	dict set TopLevelPortInterface transmitter_s_axi_awready ArithmeticType xlUnsigned
	dict set TopLevelPortInterface transmitter_s_axi_awready BinaryPoint 0
	dict set TopLevelPortInterface transmitter_s_axi_awready Width 1
	dict set TopLevelPortInterface transmitter_s_axi_awready DatFile {}
	dict set TopLevelPortInterface transmitter_s_axi_awready IconText {transmitter_s_axi_awready}
	dict set TopLevelPortInterface transmitter_s_axi_awready Direction out
	dict set TopLevelPortInterface transmitter_s_axi_awready Period 1
	dict set TopLevelPortInterface transmitter_s_axi_awready Interface 5
	dict set TopLevelPortInterface transmitter_s_axi_awready InterfaceName {}
	dict set TopLevelPortInterface transmitter_s_axi_awready InterfaceString {WIRE_AXI_LITE}
	dict set TopLevelPortInterface transmitter_s_axi_awready ClockDomain {}
	dict set TopLevelPortInterface transmitter_s_axi_awready Locs {}
	dict set TopLevelPortInterface transmitter_s_axi_awready IOStandard {}
	dict set TopLevelPortInterface transmitter_s_axi_wdata Name {transmitter_s_axi_wdata}
	dict set TopLevelPortInterface transmitter_s_axi_wdata Type -
	dict set TopLevelPortInterface transmitter_s_axi_wdata ArithmeticType xlUnsigned
	dict set TopLevelPortInterface transmitter_s_axi_wdata BinaryPoint 0
	dict set TopLevelPortInterface transmitter_s_axi_wdata Width 32
	dict set TopLevelPortInterface transmitter_s_axi_wdata DatFile {}
	dict set TopLevelPortInterface transmitter_s_axi_wdata IconText {transmitter_s_axi_wdata}
	dict set TopLevelPortInterface transmitter_s_axi_wdata Direction in
	dict set TopLevelPortInterface transmitter_s_axi_wdata Period 1
	dict set TopLevelPortInterface transmitter_s_axi_wdata Interface 5
	dict set TopLevelPortInterface transmitter_s_axi_wdata InterfaceName {}
	dict set TopLevelPortInterface transmitter_s_axi_wdata InterfaceString {WIRE_AXI_LITE}
	dict set TopLevelPortInterface transmitter_s_axi_wdata ClockDomain {}
	dict set TopLevelPortInterface transmitter_s_axi_wdata Locs {}
	dict set TopLevelPortInterface transmitter_s_axi_wdata IOStandard {}
	dict set TopLevelPortInterface transmitter_s_axi_wstrb Name {transmitter_s_axi_wstrb}
	dict set TopLevelPortInterface transmitter_s_axi_wstrb Type -
	dict set TopLevelPortInterface transmitter_s_axi_wstrb ArithmeticType xlUnsigned
	dict set TopLevelPortInterface transmitter_s_axi_wstrb BinaryPoint 0
	dict set TopLevelPortInterface transmitter_s_axi_wstrb Width 4
	dict set TopLevelPortInterface transmitter_s_axi_wstrb DatFile {}
	dict set TopLevelPortInterface transmitter_s_axi_wstrb IconText {transmitter_s_axi_wstrb}
	dict set TopLevelPortInterface transmitter_s_axi_wstrb Direction in
	dict set TopLevelPortInterface transmitter_s_axi_wstrb Period 1
	dict set TopLevelPortInterface transmitter_s_axi_wstrb Interface 5
	dict set TopLevelPortInterface transmitter_s_axi_wstrb InterfaceName {}
	dict set TopLevelPortInterface transmitter_s_axi_wstrb InterfaceString {WIRE_AXI_LITE}
	dict set TopLevelPortInterface transmitter_s_axi_wstrb ClockDomain {}
	dict set TopLevelPortInterface transmitter_s_axi_wstrb Locs {}
	dict set TopLevelPortInterface transmitter_s_axi_wstrb IOStandard {}
	dict set TopLevelPortInterface transmitter_s_axi_wvalid Name {transmitter_s_axi_wvalid}
	dict set TopLevelPortInterface transmitter_s_axi_wvalid Type -
	dict set TopLevelPortInterface transmitter_s_axi_wvalid ArithmeticType xlUnsigned
	dict set TopLevelPortInterface transmitter_s_axi_wvalid BinaryPoint 0
	dict set TopLevelPortInterface transmitter_s_axi_wvalid Width 1
	dict set TopLevelPortInterface transmitter_s_axi_wvalid DatFile {}
	dict set TopLevelPortInterface transmitter_s_axi_wvalid IconText {transmitter_s_axi_wvalid}
	dict set TopLevelPortInterface transmitter_s_axi_wvalid Direction in
	dict set TopLevelPortInterface transmitter_s_axi_wvalid Period 1
	dict set TopLevelPortInterface transmitter_s_axi_wvalid Interface 5
	dict set TopLevelPortInterface transmitter_s_axi_wvalid InterfaceName {}
	dict set TopLevelPortInterface transmitter_s_axi_wvalid InterfaceString {WIRE_AXI_LITE}
	dict set TopLevelPortInterface transmitter_s_axi_wvalid ClockDomain {}
	dict set TopLevelPortInterface transmitter_s_axi_wvalid Locs {}
	dict set TopLevelPortInterface transmitter_s_axi_wvalid IOStandard {}
	dict set TopLevelPortInterface transmitter_s_axi_wready Name {transmitter_s_axi_wready}
	dict set TopLevelPortInterface transmitter_s_axi_wready Type -
	dict set TopLevelPortInterface transmitter_s_axi_wready ArithmeticType xlUnsigned
	dict set TopLevelPortInterface transmitter_s_axi_wready BinaryPoint 0
	dict set TopLevelPortInterface transmitter_s_axi_wready Width 1
	dict set TopLevelPortInterface transmitter_s_axi_wready DatFile {}
	dict set TopLevelPortInterface transmitter_s_axi_wready IconText {transmitter_s_axi_wready}
	dict set TopLevelPortInterface transmitter_s_axi_wready Direction out
	dict set TopLevelPortInterface transmitter_s_axi_wready Period 1
	dict set TopLevelPortInterface transmitter_s_axi_wready Interface 5
	dict set TopLevelPortInterface transmitter_s_axi_wready InterfaceName {}
	dict set TopLevelPortInterface transmitter_s_axi_wready InterfaceString {WIRE_AXI_LITE}
	dict set TopLevelPortInterface transmitter_s_axi_wready ClockDomain {}
	dict set TopLevelPortInterface transmitter_s_axi_wready Locs {}
	dict set TopLevelPortInterface transmitter_s_axi_wready IOStandard {}
	dict set TopLevelPortInterface transmitter_s_axi_bresp Name {transmitter_s_axi_bresp}
	dict set TopLevelPortInterface transmitter_s_axi_bresp Type -
	dict set TopLevelPortInterface transmitter_s_axi_bresp ArithmeticType xlUnsigned
	dict set TopLevelPortInterface transmitter_s_axi_bresp BinaryPoint 0
	dict set TopLevelPortInterface transmitter_s_axi_bresp Width 2
	dict set TopLevelPortInterface transmitter_s_axi_bresp DatFile {}
	dict set TopLevelPortInterface transmitter_s_axi_bresp IconText {transmitter_s_axi_bresp}
	dict set TopLevelPortInterface transmitter_s_axi_bresp Direction out
	dict set TopLevelPortInterface transmitter_s_axi_bresp Period 1
	dict set TopLevelPortInterface transmitter_s_axi_bresp Interface 5
	dict set TopLevelPortInterface transmitter_s_axi_bresp InterfaceName {}
	dict set TopLevelPortInterface transmitter_s_axi_bresp InterfaceString {WIRE_AXI_LITE}
	dict set TopLevelPortInterface transmitter_s_axi_bresp ClockDomain {}
	dict set TopLevelPortInterface transmitter_s_axi_bresp Locs {}
	dict set TopLevelPortInterface transmitter_s_axi_bresp IOStandard {}
	dict set TopLevelPortInterface transmitter_s_axi_bvalid Name {transmitter_s_axi_bvalid}
	dict set TopLevelPortInterface transmitter_s_axi_bvalid Type -
	dict set TopLevelPortInterface transmitter_s_axi_bvalid ArithmeticType xlUnsigned
	dict set TopLevelPortInterface transmitter_s_axi_bvalid BinaryPoint 0
	dict set TopLevelPortInterface transmitter_s_axi_bvalid Width 1
	dict set TopLevelPortInterface transmitter_s_axi_bvalid DatFile {}
	dict set TopLevelPortInterface transmitter_s_axi_bvalid IconText {transmitter_s_axi_bvalid}
	dict set TopLevelPortInterface transmitter_s_axi_bvalid Direction out
	dict set TopLevelPortInterface transmitter_s_axi_bvalid Period 1
	dict set TopLevelPortInterface transmitter_s_axi_bvalid Interface 5
	dict set TopLevelPortInterface transmitter_s_axi_bvalid InterfaceName {}
	dict set TopLevelPortInterface transmitter_s_axi_bvalid InterfaceString {WIRE_AXI_LITE}
	dict set TopLevelPortInterface transmitter_s_axi_bvalid ClockDomain {}
	dict set TopLevelPortInterface transmitter_s_axi_bvalid Locs {}
	dict set TopLevelPortInterface transmitter_s_axi_bvalid IOStandard {}
	dict set TopLevelPortInterface transmitter_s_axi_bready Name {transmitter_s_axi_bready}
	dict set TopLevelPortInterface transmitter_s_axi_bready Type -
	dict set TopLevelPortInterface transmitter_s_axi_bready ArithmeticType xlUnsigned
	dict set TopLevelPortInterface transmitter_s_axi_bready BinaryPoint 0
	dict set TopLevelPortInterface transmitter_s_axi_bready Width 1
	dict set TopLevelPortInterface transmitter_s_axi_bready DatFile {}
	dict set TopLevelPortInterface transmitter_s_axi_bready IconText {transmitter_s_axi_bready}
	dict set TopLevelPortInterface transmitter_s_axi_bready Direction in
	dict set TopLevelPortInterface transmitter_s_axi_bready Period 1
	dict set TopLevelPortInterface transmitter_s_axi_bready Interface 5
	dict set TopLevelPortInterface transmitter_s_axi_bready InterfaceName {}
	dict set TopLevelPortInterface transmitter_s_axi_bready InterfaceString {WIRE_AXI_LITE}
	dict set TopLevelPortInterface transmitter_s_axi_bready ClockDomain {}
	dict set TopLevelPortInterface transmitter_s_axi_bready Locs {}
	dict set TopLevelPortInterface transmitter_s_axi_bready IOStandard {}
	dict set TopLevelPortInterface transmitter_s_axi_araddr Name {transmitter_s_axi_araddr}
	dict set TopLevelPortInterface transmitter_s_axi_araddr Type -
	dict set TopLevelPortInterface transmitter_s_axi_araddr ArithmeticType xlUnsigned
	dict set TopLevelPortInterface transmitter_s_axi_araddr BinaryPoint 0
	dict set TopLevelPortInterface transmitter_s_axi_araddr Width 4
	dict set TopLevelPortInterface transmitter_s_axi_araddr DatFile {}
	dict set TopLevelPortInterface transmitter_s_axi_araddr IconText {transmitter_s_axi_araddr}
	dict set TopLevelPortInterface transmitter_s_axi_araddr Direction in
	dict set TopLevelPortInterface transmitter_s_axi_araddr Period 1
	dict set TopLevelPortInterface transmitter_s_axi_araddr Interface 5
	dict set TopLevelPortInterface transmitter_s_axi_araddr InterfaceName {}
	dict set TopLevelPortInterface transmitter_s_axi_araddr InterfaceString {WIRE_AXI_LITE}
	dict set TopLevelPortInterface transmitter_s_axi_araddr ClockDomain {}
	dict set TopLevelPortInterface transmitter_s_axi_araddr Locs {}
	dict set TopLevelPortInterface transmitter_s_axi_araddr IOStandard {}
	dict set TopLevelPortInterface transmitter_s_axi_arvalid Name {transmitter_s_axi_arvalid}
	dict set TopLevelPortInterface transmitter_s_axi_arvalid Type -
	dict set TopLevelPortInterface transmitter_s_axi_arvalid ArithmeticType xlUnsigned
	dict set TopLevelPortInterface transmitter_s_axi_arvalid BinaryPoint 0
	dict set TopLevelPortInterface transmitter_s_axi_arvalid Width 1
	dict set TopLevelPortInterface transmitter_s_axi_arvalid DatFile {}
	dict set TopLevelPortInterface transmitter_s_axi_arvalid IconText {transmitter_s_axi_arvalid}
	dict set TopLevelPortInterface transmitter_s_axi_arvalid Direction in
	dict set TopLevelPortInterface transmitter_s_axi_arvalid Period 1
	dict set TopLevelPortInterface transmitter_s_axi_arvalid Interface 5
	dict set TopLevelPortInterface transmitter_s_axi_arvalid InterfaceName {}
	dict set TopLevelPortInterface transmitter_s_axi_arvalid InterfaceString {WIRE_AXI_LITE}
	dict set TopLevelPortInterface transmitter_s_axi_arvalid ClockDomain {}
	dict set TopLevelPortInterface transmitter_s_axi_arvalid Locs {}
	dict set TopLevelPortInterface transmitter_s_axi_arvalid IOStandard {}
	dict set TopLevelPortInterface transmitter_s_axi_arready Name {transmitter_s_axi_arready}
	dict set TopLevelPortInterface transmitter_s_axi_arready Type -
	dict set TopLevelPortInterface transmitter_s_axi_arready ArithmeticType xlUnsigned
	dict set TopLevelPortInterface transmitter_s_axi_arready BinaryPoint 0
	dict set TopLevelPortInterface transmitter_s_axi_arready Width 1
	dict set TopLevelPortInterface transmitter_s_axi_arready DatFile {}
	dict set TopLevelPortInterface transmitter_s_axi_arready IconText {transmitter_s_axi_arready}
	dict set TopLevelPortInterface transmitter_s_axi_arready Direction out
	dict set TopLevelPortInterface transmitter_s_axi_arready Period 1
	dict set TopLevelPortInterface transmitter_s_axi_arready Interface 5
	dict set TopLevelPortInterface transmitter_s_axi_arready InterfaceName {}
	dict set TopLevelPortInterface transmitter_s_axi_arready InterfaceString {WIRE_AXI_LITE}
	dict set TopLevelPortInterface transmitter_s_axi_arready ClockDomain {}
	dict set TopLevelPortInterface transmitter_s_axi_arready Locs {}
	dict set TopLevelPortInterface transmitter_s_axi_arready IOStandard {}
	dict set TopLevelPortInterface transmitter_s_axi_rdata Name {transmitter_s_axi_rdata}
	dict set TopLevelPortInterface transmitter_s_axi_rdata Type -
	dict set TopLevelPortInterface transmitter_s_axi_rdata ArithmeticType xlUnsigned
	dict set TopLevelPortInterface transmitter_s_axi_rdata BinaryPoint 0
	dict set TopLevelPortInterface transmitter_s_axi_rdata Width 32
	dict set TopLevelPortInterface transmitter_s_axi_rdata DatFile {}
	dict set TopLevelPortInterface transmitter_s_axi_rdata IconText {transmitter_s_axi_rdata}
	dict set TopLevelPortInterface transmitter_s_axi_rdata Direction out
	dict set TopLevelPortInterface transmitter_s_axi_rdata Period 1
	dict set TopLevelPortInterface transmitter_s_axi_rdata Interface 5
	dict set TopLevelPortInterface transmitter_s_axi_rdata InterfaceName {}
	dict set TopLevelPortInterface transmitter_s_axi_rdata InterfaceString {WIRE_AXI_LITE}
	dict set TopLevelPortInterface transmitter_s_axi_rdata ClockDomain {}
	dict set TopLevelPortInterface transmitter_s_axi_rdata Locs {}
	dict set TopLevelPortInterface transmitter_s_axi_rdata IOStandard {}
	dict set TopLevelPortInterface transmitter_s_axi_rresp Name {transmitter_s_axi_rresp}
	dict set TopLevelPortInterface transmitter_s_axi_rresp Type -
	dict set TopLevelPortInterface transmitter_s_axi_rresp ArithmeticType xlUnsigned
	dict set TopLevelPortInterface transmitter_s_axi_rresp BinaryPoint 0
	dict set TopLevelPortInterface transmitter_s_axi_rresp Width 2
	dict set TopLevelPortInterface transmitter_s_axi_rresp DatFile {}
	dict set TopLevelPortInterface transmitter_s_axi_rresp IconText {transmitter_s_axi_rresp}
	dict set TopLevelPortInterface transmitter_s_axi_rresp Direction out
	dict set TopLevelPortInterface transmitter_s_axi_rresp Period 1
	dict set TopLevelPortInterface transmitter_s_axi_rresp Interface 5
	dict set TopLevelPortInterface transmitter_s_axi_rresp InterfaceName {}
	dict set TopLevelPortInterface transmitter_s_axi_rresp InterfaceString {WIRE_AXI_LITE}
	dict set TopLevelPortInterface transmitter_s_axi_rresp ClockDomain {}
	dict set TopLevelPortInterface transmitter_s_axi_rresp Locs {}
	dict set TopLevelPortInterface transmitter_s_axi_rresp IOStandard {}
	dict set TopLevelPortInterface transmitter_s_axi_rvalid Name {transmitter_s_axi_rvalid}
	dict set TopLevelPortInterface transmitter_s_axi_rvalid Type -
	dict set TopLevelPortInterface transmitter_s_axi_rvalid ArithmeticType xlUnsigned
	dict set TopLevelPortInterface transmitter_s_axi_rvalid BinaryPoint 0
	dict set TopLevelPortInterface transmitter_s_axi_rvalid Width 1
	dict set TopLevelPortInterface transmitter_s_axi_rvalid DatFile {}
	dict set TopLevelPortInterface transmitter_s_axi_rvalid IconText {transmitter_s_axi_rvalid}
	dict set TopLevelPortInterface transmitter_s_axi_rvalid Direction out
	dict set TopLevelPortInterface transmitter_s_axi_rvalid Period 1
	dict set TopLevelPortInterface transmitter_s_axi_rvalid Interface 5
	dict set TopLevelPortInterface transmitter_s_axi_rvalid InterfaceName {}
	dict set TopLevelPortInterface transmitter_s_axi_rvalid InterfaceString {WIRE_AXI_LITE}
	dict set TopLevelPortInterface transmitter_s_axi_rvalid ClockDomain {}
	dict set TopLevelPortInterface transmitter_s_axi_rvalid Locs {}
	dict set TopLevelPortInterface transmitter_s_axi_rvalid IOStandard {}
	dict set TopLevelPortInterface transmitter_s_axi_rready Name {transmitter_s_axi_rready}
	dict set TopLevelPortInterface transmitter_s_axi_rready Type -
	dict set TopLevelPortInterface transmitter_s_axi_rready ArithmeticType xlUnsigned
	dict set TopLevelPortInterface transmitter_s_axi_rready BinaryPoint 0
	dict set TopLevelPortInterface transmitter_s_axi_rready Width 1
	dict set TopLevelPortInterface transmitter_s_axi_rready DatFile {}
	dict set TopLevelPortInterface transmitter_s_axi_rready IconText {transmitter_s_axi_rready}
	dict set TopLevelPortInterface transmitter_s_axi_rready Direction in
	dict set TopLevelPortInterface transmitter_s_axi_rready Period 1
	dict set TopLevelPortInterface transmitter_s_axi_rready Interface 5
	dict set TopLevelPortInterface transmitter_s_axi_rready InterfaceName {}
	dict set TopLevelPortInterface transmitter_s_axi_rready InterfaceString {WIRE_AXI_LITE}
	dict set TopLevelPortInterface transmitter_s_axi_rready ClockDomain {}
	dict set TopLevelPortInterface transmitter_s_axi_rready Locs {}
	dict set TopLevelPortInterface transmitter_s_axi_rready IOStandard {}
	dict set TopLevelPortInterface clk Name {clk}
	dict set TopLevelPortInterface clk Type -
	dict set TopLevelPortInterface clk ArithmeticType xlUnsigned
	dict set TopLevelPortInterface clk BinaryPoint 0
	dict set TopLevelPortInterface clk Width 1
	dict set TopLevelPortInterface clk DatFile {}
	dict set TopLevelPortInterface clk Direction in
	dict set TopLevelPortInterface clk Period 1
	dict set TopLevelPortInterface clk Interface 6
	dict set TopLevelPortInterface clk InterfaceName {}
	dict set TopLevelPortInterface clk InterfaceString {CLOCK}
	dict set TopLevelPortInterface clk ClockDomain {transmitter}
	dict set TopLevelPortInterface clk Locs {}
	dict set TopLevelPortInterface clk IOStandard {}
	dict set TopLevelPortInterface clk AssociatedInterfaces {transmitter_s_axi }
	dict set TopLevelPortInterface clk AssociatedResets {transmitter_aresetn }
	set MemoryMappedPort {}
	dict set MemoryMappedPort enable_data_in Name {enable_data_in}
	dict set MemoryMappedPort enable_data_in Type Bool
	dict set MemoryMappedPort enable_data_in ArithmeticType xlUnsigned
	dict set MemoryMappedPort enable_data_in BinaryPoint 0
	dict set MemoryMappedPort enable_data_in Width 1
	dict set MemoryMappedPort enable_data_in DatFile {model_v6_15022023_transmitter_config_enable_data_in.dat}
	dict set MemoryMappedPort enable_data_in AddressOffset 0
	dict set MemoryMappedPort enable_data_in IconText {enable_data_in}
	dict set MemoryMappedPort enable_data_in Direction in
	dict set MemoryMappedPort enable_data_in Period 1280
	dict set MemoryMappedPort enable_data_in Interface 2
	dict set MemoryMappedPort enable_data_in InterfaceName {}
	dict set MemoryMappedPort enable_data_in InterfaceString {CONTROL}
	dict set MemoryMappedPort enable_data_in ClockDomain {transmitter}
	dict set MemoryMappedPort enable_data_in Locs {}
	dict set MemoryMappedPort enable_data_in IOStandard {}
	dict set MemoryMappedPort observation_point Name {observation_point}
	dict set MemoryMappedPort observation_point Type UFix_32_0
	dict set MemoryMappedPort observation_point ArithmeticType xlUnsigned
	dict set MemoryMappedPort observation_point BinaryPoint 0
	dict set MemoryMappedPort observation_point Width 32
	dict set MemoryMappedPort observation_point DatFile {model_v6_15022023_transmitter_config_observation_point.dat}
	dict set MemoryMappedPort observation_point AddressOffset 12
	dict set MemoryMappedPort observation_point IconText {observation_point}
	dict set MemoryMappedPort observation_point Direction in
	dict set MemoryMappedPort observation_point Period 2
	dict set MemoryMappedPort observation_point Interface 2
	dict set MemoryMappedPort observation_point InterfaceName {}
	dict set MemoryMappedPort observation_point InterfaceString {CONTROL}
	dict set MemoryMappedPort observation_point ClockDomain {transmitter}
	dict set MemoryMappedPort observation_point Locs {}
	dict set MemoryMappedPort observation_point IOStandard {}
	dict set MemoryMappedPort modulation_in Name {modulation_in}
	dict set MemoryMappedPort modulation_in Type UFix_16_0
	dict set MemoryMappedPort modulation_in ArithmeticType xlUnsigned
	dict set MemoryMappedPort modulation_in BinaryPoint 0
	dict set MemoryMappedPort modulation_in Width 16
	dict set MemoryMappedPort modulation_in DatFile {model_v6_15022023_transmitter_config_modulation_in.dat}
	dict set MemoryMappedPort modulation_in AddressOffset 8
	dict set MemoryMappedPort modulation_in IconText {modulation_in}
	dict set MemoryMappedPort modulation_in Direction in
	dict set MemoryMappedPort modulation_in Period 1280
	dict set MemoryMappedPort modulation_in Interface 2
	dict set MemoryMappedPort modulation_in InterfaceName {}
	dict set MemoryMappedPort modulation_in InterfaceString {CONTROL}
	dict set MemoryMappedPort modulation_in ClockDomain {transmitter}
	dict set MemoryMappedPort modulation_in Locs {}
	dict set MemoryMappedPort modulation_in IOStandard {}
	dict set MemoryMappedPort enable_tx_in Name {enable_tx_in}
	dict set MemoryMappedPort enable_tx_in Type Bool
	dict set MemoryMappedPort enable_tx_in ArithmeticType xlUnsigned
	dict set MemoryMappedPort enable_tx_in BinaryPoint 0
	dict set MemoryMappedPort enable_tx_in Width 1
	dict set MemoryMappedPort enable_tx_in DatFile {model_v6_15022023_transmitter_config_enable_tx_in.dat}
	dict set MemoryMappedPort enable_tx_in AddressOffset 4
	dict set MemoryMappedPort enable_tx_in IconText {enable_tx_in}
	dict set MemoryMappedPort enable_tx_in Direction in
	dict set MemoryMappedPort enable_tx_in Period 1280
	dict set MemoryMappedPort enable_tx_in Interface 2
	dict set MemoryMappedPort enable_tx_in InterfaceName {}
	dict set MemoryMappedPort enable_tx_in InterfaceString {CONTROL}
	dict set MemoryMappedPort enable_tx_in ClockDomain {transmitter}
	dict set MemoryMappedPort enable_tx_in Locs {}
	dict set MemoryMappedPort enable_tx_in IOStandard {}
}

source SgPaProject.tcl
::xilinx::dsp::planaheadworker::dsp_create_project