-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\untitled\tx_mod_ip_dut.vhd
-- Created: 2023-02-16 14:09:43
-- 
-- Generated by MATLAB 9.10 and HDL Coder 3.18
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: tx_mod_ip_dut
-- Source Path: tx_mod_ip/tx_mod_ip_dut
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY tx_mod_ip_dut IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        dut_enable                        :   IN    std_logic;  -- ufix1
        modulation                        :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
        enable                            :   IN    std_logic;  -- ufix1
        ce_out                            :   OUT   std_logic;  -- ufix1
        tdata                             :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        valid                             :   OUT   std_logic  -- ufix1
        );
END tx_mod_ip_dut;


ARCHITECTURE rtl OF tx_mod_ip_dut IS

  -- Component Declarations
  COMPONENT tx_mod_ip_src_Modulation
    PORT( clk                             :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          reset                           :   IN    std_logic;
          modulation                      :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
          enable                          :   IN    std_logic;  -- ufix1
          ce_out                          :   OUT   std_logic;  -- ufix1
          tdata                           :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          valid                           :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : tx_mod_ip_src_Modulation
    USE ENTITY work.tx_mod_ip_src_Modulation(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL enable_sig                       : std_logic;  -- ufix1
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL tdata_sig                        : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL valid_sig                        : std_logic;  -- ufix1

BEGIN
  u_tx_mod_ip_src_Modulation : tx_mod_ip_src_Modulation
    PORT MAP( clk => clk,
              clk_enable => enb,
              reset => reset,
              modulation => modulation,  -- ufix8
              enable => enable_sig,  -- ufix1
              ce_out => ce_out_sig,  -- ufix1
              tdata => tdata_sig,  -- ufix32
              valid => valid_sig  -- ufix1
              );

  enable_sig <= enable;

  enb <= dut_enable;

  ce_out <= ce_out_sig;

  tdata <= tdata_sig;

  valid <= valid_sig;

END rtl;

