-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\Tx_Signal\Tx_Signal_ip_src_AXIS_S.vhd
-- Created: 2023-02-16 15:23:47
-- 
-- Generated by MATLAB 9.10 and HDL Coder 3.18
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Tx_Signal_ip_src_AXIS_S
-- Source Path: Tx_Signal/Tx_Signal/AXIS_S
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Tx_Signal_ip_src_AXIS_S IS
  PORT( s_tready                          :   OUT   std_logic
        );
END Tx_Signal_ip_src_AXIS_S;


ARCHITECTURE rtl OF Tx_Signal_ip_src_AXIS_S IS

  -- Signals
  SIGNAL s_axis_tready_out1               : std_logic;

BEGIN
  s_axis_tready_out1 <= '1';

  s_tready <= s_axis_tready_out1;

END rtl;

