-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\Tx_Signal\Tx_Signal_ip_src_QAM256_Generator.vhd
-- Created: 2023-02-16 15:23:47
-- 
-- Generated by MATLAB 9.10 and HDL Coder 3.18
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Tx_Signal_ip_src_QAM256_Generator
-- Source Path: Tx_Signal/Tx_Signal/Modulation/Signal Generator/Variable Modulator/QAM256 Generator
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Tx_Signal_ip_src_QAM256_Generator IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        Data                              :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        Reset_1                           :   IN    std_logic;
        Enable                            :   IN    std_logic;
        I_symbols                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        Q_symbols                         :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
        );
END Tx_Signal_ip_src_QAM256_Generator;


ARCHITECTURE rtl OF Tx_Signal_ip_src_QAM256_Generator IS

  -- Component Declarations
  COMPONENT Tx_Signal_ip_src_complement_re_block
    PORT( d_in                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          d_out                           :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
          );
  END COMPONENT;

  COMPONENT Tx_Signal_ip_src_complement_im_block
    PORT( d_in                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          d_out                           :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Tx_Signal_ip_src_complement_re_block
    USE ENTITY work.Tx_Signal_ip_src_complement_re_block(rtl);

  FOR ALL : Tx_Signal_ip_src_complement_im_block
    USE ENTITY work.Tx_Signal_ip_src_complement_im_block(rtl);

  -- Signals
  SIGNAL Data_unsigned                    : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Bit_Slice3_out1                  : std_logic;  -- ufix1
  SIGNAL Bit_Slice2_out1                  : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL Constant1_out1                   : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Constant5_out1                   : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Constant2_out1                   : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Constant6_out1                   : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Constant7_out1                   : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Constant3_out1                   : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Constant4_out1                   : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Constant8_out1                   : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Multiport_Switch_out1            : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL complement_re_out1               : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL complement_re_out1_signed        : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Multiport_Switch2_out1           : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Delay1_bypass                    : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL Delay1_reg                       : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL Delay1_bypass_next               : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Delay1_delay_out                 : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Delay1_out1                      : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Bit_Slice4_out1                  : std_logic;  -- ufix1
  SIGNAL Bit_Slice1_out1                  : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL Multiport_Switch1_out1           : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL complement_im_out1               : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL complement_im_out1_signed        : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Multiport_Switch3_out1           : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Delay2_bypass                    : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL Delay2_reg                       : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL Delay2_bypass_next               : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Delay2_delay_out                 : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Delay2_out1                      : signed(15 DOWNTO 0);  -- sfix16_En14

BEGIN
  u_complement_re : Tx_Signal_ip_src_complement_re_block
    PORT MAP( d_in => std_logic_vector(Multiport_Switch_out1),  -- sfix16_En14
              d_out => complement_re_out1  -- sfix16_En14
              );

  u_complement_im : Tx_Signal_ip_src_complement_im_block
    PORT MAP( d_in => std_logic_vector(Multiport_Switch1_out1),  -- sfix16_En14
              d_out => complement_im_out1  -- sfix16_En14
              );

  Data_unsigned <= unsigned(Data);

  Bit_Slice3_out1 <= Data_unsigned(6);

  Bit_Slice2_out1 <= Data_unsigned(2 DOWNTO 0);

  Constant1_out1 <= to_signed(16#40CD#, 16);

  Constant5_out1 <= to_signed(16#3829#, 16);

  Constant2_out1 <= to_signed(16#2F85#, 16);

  Constant6_out1 <= to_signed(16#26E1#, 16);

  Constant7_out1 <= to_signed(16#1E3D#, 16);

  Constant3_out1 <= to_signed(16#159A#, 16);

  Constant4_out1 <= to_signed(16#0CF6#, 16);

  Constant8_out1 <= to_signed(16#0452#, 16);

  
  Multiport_Switch_out1 <= Constant1_out1 WHEN Bit_Slice2_out1 = to_unsigned(16#0#, 3) ELSE
      Constant5_out1 WHEN Bit_Slice2_out1 = to_unsigned(16#1#, 3) ELSE
      Constant2_out1 WHEN Bit_Slice2_out1 = to_unsigned(16#2#, 3) ELSE
      Constant6_out1 WHEN Bit_Slice2_out1 = to_unsigned(16#3#, 3) ELSE
      Constant7_out1 WHEN Bit_Slice2_out1 = to_unsigned(16#4#, 3) ELSE
      Constant3_out1 WHEN Bit_Slice2_out1 = to_unsigned(16#5#, 3) ELSE
      Constant4_out1 WHEN Bit_Slice2_out1 = to_unsigned(16#6#, 3) ELSE
      Constant8_out1;

  complement_re_out1_signed <= signed(complement_re_out1);

  
  Multiport_Switch2_out1 <= Multiport_Switch_out1 WHEN Bit_Slice3_out1 = '0' ELSE
      complement_re_out1_signed;

  Delay1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay1_bypass <= to_signed(16#0000#, 16);
      Delay1_reg <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Enable = '1' THEN
          IF Reset_1 = '1' THEN
            Delay1_bypass <= to_signed(16#0000#, 16);
            Delay1_reg <= to_signed(16#0000#, 16);
          ELSE 
            Delay1_bypass <= Delay1_bypass_next;
            Delay1_reg <= Multiport_Switch2_out1;
          END IF;
        END IF;
      END IF;
    END IF;
  END PROCESS Delay1_process;

  
  Delay1_delay_out <= to_signed(16#0000#, 16) WHEN Reset_1 = '1' ELSE
      Delay1_reg;
  
  Delay1_out1 <= Delay1_delay_out WHEN Enable = '1' ELSE
      Delay1_bypass;
  Delay1_bypass_next <= Delay1_delay_out;

  I_symbols <= std_logic_vector(Delay1_out1);

  Bit_Slice4_out1 <= Data_unsigned(7);

  Bit_Slice1_out1 <= Data_unsigned(5 DOWNTO 3);

  
  Multiport_Switch1_out1 <= Constant1_out1 WHEN Bit_Slice1_out1 = to_unsigned(16#0#, 3) ELSE
      Constant5_out1 WHEN Bit_Slice1_out1 = to_unsigned(16#1#, 3) ELSE
      Constant2_out1 WHEN Bit_Slice1_out1 = to_unsigned(16#2#, 3) ELSE
      Constant6_out1 WHEN Bit_Slice1_out1 = to_unsigned(16#3#, 3) ELSE
      Constant7_out1 WHEN Bit_Slice1_out1 = to_unsigned(16#4#, 3) ELSE
      Constant3_out1 WHEN Bit_Slice1_out1 = to_unsigned(16#5#, 3) ELSE
      Constant4_out1 WHEN Bit_Slice1_out1 = to_unsigned(16#6#, 3) ELSE
      Constant8_out1;

  complement_im_out1_signed <= signed(complement_im_out1);

  
  Multiport_Switch3_out1 <= Multiport_Switch1_out1 WHEN Bit_Slice4_out1 = '0' ELSE
      complement_im_out1_signed;

  Delay2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay2_bypass <= to_signed(16#0000#, 16);
      Delay2_reg <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Enable = '1' THEN
          IF Reset_1 = '1' THEN
            Delay2_bypass <= to_signed(16#0000#, 16);
            Delay2_reg <= to_signed(16#0000#, 16);
          ELSE 
            Delay2_bypass <= Delay2_bypass_next;
            Delay2_reg <= Multiport_Switch3_out1;
          END IF;
        END IF;
      END IF;
    END IF;
  END PROCESS Delay2_process;

  
  Delay2_delay_out <= to_signed(16#0000#, 16) WHEN Reset_1 = '1' ELSE
      Delay2_reg;
  
  Delay2_out1 <= Delay2_delay_out WHEN Enable = '1' ELSE
      Delay2_bypass;
  Delay2_bypass_next <= Delay2_delay_out;

  Q_symbols <= std_logic_vector(Delay2_out1);

END rtl;

