-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\Tx_Signal\Tx_Signal_ip_src_Type_Conv.vhd
-- Created: 2023-02-16 15:23:47
-- 
-- Generated by MATLAB 9.10 and HDL Coder 3.18
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Tx_Signal_ip_src_Type_Conv
-- Source Path: Tx_Signal/Tx_Signal/Modulation/Type Conv
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Tx_Signal_ip_src_Type_Conv IS
  PORT( re_tdata                          :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        im_tdata                          :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        tdata                             :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
        );
END Tx_Signal_ip_src_Type_Conv;


ARCHITECTURE rtl OF Tx_Signal_ip_src_Type_Conv IS

  -- Signals
  SIGNAL im_tdata_signed                  : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Data_Type_Conversion1_out1       : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL re_tdata_signed                  : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Data_Type_Conversion_out1        : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Bit_Concat_out1                  : unsigned(31 DOWNTO 0);  -- uint32

BEGIN
  im_tdata_signed <= signed(im_tdata);

  Data_Type_Conversion1_out1 <= unsigned(im_tdata_signed);

  re_tdata_signed <= signed(re_tdata);

  Data_Type_Conversion_out1 <= unsigned(re_tdata_signed);

  Bit_Concat_out1 <= Data_Type_Conversion1_out1 & Data_Type_Conversion_out1;

  tdata <= std_logic_vector(Bit_Concat_out1);

END rtl;

