-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\Tx_Signal\Tx_Signal_ip_src_Modulation.vhd
-- Created: 2023-02-16 15:23:47
-- 
-- Generated by MATLAB 9.10 and HDL Coder 3.18
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Tx_Signal_ip_src_Modulation
-- Source Path: Tx_Signal/Tx_Signal/Modulation
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Tx_Signal_ip_src_Modulation IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        modulation                        :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        enable_tx                         :   IN    std_logic;
        tdata                             :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        valid                             :   OUT   std_logic
        );
END Tx_Signal_ip_src_Modulation;


ARCHITECTURE rtl OF Tx_Signal_ip_src_Modulation IS

  -- Component Declarations
  COMPONENT Tx_Signal_ip_src_Signal_Generator
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Modulation                      :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          Reset_1                         :   IN    std_logic;
          Enable                          :   IN    std_logic;
          re_tdata                        :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          im_tdata                        :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          m_axis_tvalid                   :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT Tx_Signal_ip_src_Type_Conv
    PORT( re_tdata                        :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          im_tdata                        :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          tdata                           :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Tx_Signal_ip_src_Signal_Generator
    USE ENTITY work.Tx_Signal_ip_src_Signal_Generator(rtl);

  FOR ALL : Tx_Signal_ip_src_Type_Conv
    USE ENTITY work.Tx_Signal_ip_src_Type_Conv(rtl);

  -- Signals
  SIGNAL Constant1_out1                   : std_logic;
  SIGNAL Signal_Generator_out1            : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Signal_Generator_out2            : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Signal_Generator_out3            : std_logic;
  SIGNAL y                                : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_Signal_Generator : Tx_Signal_ip_src_Signal_Generator
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              Modulation => modulation,  -- uint16
              Reset_1 => Constant1_out1,
              Enable => enable_tx,
              re_tdata => Signal_Generator_out1,  -- sfix16_En14
              im_tdata => Signal_Generator_out2,  -- sfix16_En14
              m_axis_tvalid => Signal_Generator_out3
              );

  u_Type_Conv : Tx_Signal_ip_src_Type_Conv
    PORT MAP( re_tdata => Signal_Generator_out1,  -- sfix16_En14
              im_tdata => Signal_Generator_out2,  -- sfix16_En14
              tdata => y  -- uint32
              );

  Constant1_out1 <= '0';

  tdata <= y;

  valid <= Signal_Generator_out3;

END rtl;

