-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\Tx_Signal\Tx_Signal_ip_src_QAM32_Generator.vhd
-- Created: 2023-02-16 15:23:47
-- 
-- Generated by MATLAB 9.10 and HDL Coder 3.18
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Tx_Signal_ip_src_QAM32_Generator
-- Source Path: Tx_Signal/Tx_Signal/Modulation/Signal Generator/Variable Modulator/QAM32 Generator
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Tx_Signal_ip_src_QAM32_Generator IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        Data                              :   IN    std_logic_vector(4 DOWNTO 0);  -- ufix5
        Reset_1                           :   IN    std_logic;
        Enable                            :   IN    std_logic;
        I_symbols                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        Q_symbols                         :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
        );
END Tx_Signal_ip_src_QAM32_Generator;


ARCHITECTURE rtl OF Tx_Signal_ip_src_QAM32_Generator IS

  -- Component Declarations
  COMPONENT Tx_Signal_ip_src_complement_re_block1
    PORT( d_in                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          d_out                           :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
          );
  END COMPONENT;

  COMPONENT Tx_Signal_ip_src_complement_block
    PORT( d_in                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          d_out                           :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
          );
  END COMPONENT;

  COMPONENT Tx_Signal_ip_src_complement_im_block1
    PORT( d_in                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          d_out                           :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Tx_Signal_ip_src_complement_re_block1
    USE ENTITY work.Tx_Signal_ip_src_complement_re_block1(rtl);

  FOR ALL : Tx_Signal_ip_src_complement_block
    USE ENTITY work.Tx_Signal_ip_src_complement_block(rtl);

  FOR ALL : Tx_Signal_ip_src_complement_im_block1
    USE ENTITY work.Tx_Signal_ip_src_complement_im_block1(rtl);

  -- Signals
  SIGNAL Data_unsigned                    : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL Bit_Slice5_out1                  : std_logic;  -- ufix1
  SIGNAL Bit_Slice4_out1                  : std_logic;  -- ufix1
  SIGNAL Bit_Slice3_out1                  : std_logic;  -- ufix1
  SIGNAL Constant3_out1                   : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Constant6_out1                   : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Multiport_Switch2_out1           : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Bit_Slice1_out1                  : std_logic;  -- ufix1
  SIGNAL Bit_Slice2_out1                  : std_logic;  -- ufix1
  SIGNAL Multiport_Switch4_out1           : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Constant2_out1                   : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Constant4_out1                   : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Multiport_Switch1_out1           : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Multiport_Switch5_out1           : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Multiport_Switch6_out1           : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL complement_re_out1               : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL complement_re_out1_signed        : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Multiport_Switch7_out1           : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Delay1_bypass                    : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL Delay1_reg                       : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL Delay1_bypass_next               : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Delay1_delay_out                 : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Delay1_out1                      : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL complement_out1                  : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL complement_out1_signed           : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Multiport_Switch3_out1           : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL complement_im_out1               : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL complement_im_out1_signed        : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Multiport_Switch8_out1           : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Delay2_bypass                    : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL Delay2_reg                       : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL Delay2_bypass_next               : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Delay2_delay_out                 : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Delay2_out1                      : signed(15 DOWNTO 0);  -- sfix16_En14

BEGIN
  u_complement_re : Tx_Signal_ip_src_complement_re_block1
    PORT MAP( d_in => std_logic_vector(Multiport_Switch6_out1),  -- sfix16_En14
              d_out => complement_re_out1  -- sfix16_En14
              );

  u_complement : Tx_Signal_ip_src_complement_block
    PORT MAP( d_in => std_logic_vector(Multiport_Switch2_out1),  -- sfix16_En14
              d_out => complement_out1  -- sfix16_En14
              );

  u_complement_im : Tx_Signal_ip_src_complement_im_block1
    PORT MAP( d_in => std_logic_vector(Multiport_Switch3_out1),  -- sfix16_En14
              d_out => complement_im_out1  -- sfix16_En14
              );

  Data_unsigned <= unsigned(Data);

  Bit_Slice5_out1 <= Data_unsigned(4);

  Bit_Slice4_out1 <= Data_unsigned(3);

  Bit_Slice3_out1 <= Data_unsigned(0);

  Constant3_out1 <= to_signed(16#0CCD#, 16);

  Constant6_out1 <= to_signed(16#2666#, 16);

  
  Multiport_Switch2_out1 <= Constant3_out1 WHEN Bit_Slice3_out1 = '0' ELSE
      Constant6_out1;

  Bit_Slice1_out1 <= Data_unsigned(2);

  Bit_Slice2_out1 <= Data_unsigned(1);

  
  Multiport_Switch4_out1 <= Constant3_out1 WHEN Bit_Slice2_out1 = '0' ELSE
      Constant6_out1;

  Constant2_out1 <= to_signed(16#4000#, 16);

  Constant4_out1 <= to_signed(-16#4000#, 16);

  
  Multiport_Switch1_out1 <= Constant2_out1 WHEN Bit_Slice2_out1 = '0' ELSE
      Constant4_out1;

  
  Multiport_Switch5_out1 <= Multiport_Switch4_out1 WHEN Bit_Slice1_out1 = '0' ELSE
      Multiport_Switch1_out1;

  
  Multiport_Switch6_out1 <= Multiport_Switch2_out1 WHEN Bit_Slice4_out1 = '0' ELSE
      Multiport_Switch5_out1;

  complement_re_out1_signed <= signed(complement_re_out1);

  
  Multiport_Switch7_out1 <= Multiport_Switch6_out1 WHEN Bit_Slice5_out1 = '0' ELSE
      complement_re_out1_signed;

  Delay1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay1_bypass <= to_signed(16#0000#, 16);
      Delay1_reg <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Enable = '1' THEN
          IF Reset_1 = '1' THEN
            Delay1_bypass <= to_signed(16#0000#, 16);
            Delay1_reg <= to_signed(16#0000#, 16);
          ELSE 
            Delay1_bypass <= Delay1_bypass_next;
            Delay1_reg <= Multiport_Switch7_out1;
          END IF;
        END IF;
      END IF;
    END IF;
  END PROCESS Delay1_process;

  
  Delay1_delay_out <= to_signed(16#0000#, 16) WHEN Reset_1 = '1' ELSE
      Delay1_reg;
  
  Delay1_out1 <= Delay1_delay_out WHEN Enable = '1' ELSE
      Delay1_bypass;
  Delay1_bypass_next <= Delay1_delay_out;

  I_symbols <= std_logic_vector(Delay1_out1);

  complement_out1_signed <= signed(complement_out1);

  
  Multiport_Switch3_out1 <= Multiport_Switch5_out1 WHEN Bit_Slice4_out1 = '0' ELSE
      complement_out1_signed;

  complement_im_out1_signed <= signed(complement_im_out1);

  
  Multiport_Switch8_out1 <= Multiport_Switch3_out1 WHEN Bit_Slice5_out1 = '0' ELSE
      complement_im_out1_signed;

  Delay2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay2_bypass <= to_signed(16#0000#, 16);
      Delay2_reg <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Enable = '1' THEN
          IF Reset_1 = '1' THEN
            Delay2_bypass <= to_signed(16#0000#, 16);
            Delay2_reg <= to_signed(16#0000#, 16);
          ELSE 
            Delay2_bypass <= Delay2_bypass_next;
            Delay2_reg <= Multiport_Switch8_out1;
          END IF;
        END IF;
      END IF;
    END IF;
  END PROCESS Delay2_process;

  
  Delay2_delay_out <= to_signed(16#0000#, 16) WHEN Reset_1 = '1' ELSE
      Delay2_reg;
  
  Delay2_out1 <= Delay2_delay_out WHEN Enable = '1' ELSE
      Delay2_bypass;
  Delay2_bypass_next <= Delay2_delay_out;

  Q_symbols <= std_logic_vector(Delay2_out1);

END rtl;

